version: "2"
services:
  cms-utilization-postgres:
    image: sudowing/cms-utilization-db:develop
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
      - ./volumes/tmp:/tmp
      - ./etl:/etl
      - ./etl/scripts/schema.load.sh:/docker-entrypoint-initdb.d/schema.load.sh
