version: "2"
services:
  cms-utilization-postgres:
    image: sudowing/cms-utilization-db:master
    restart: always
    env_file:
      - './.env'
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
